2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_setup.py:_flush():67] Configure stats pid to 1695807
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_setup.py:_flush():67] Loading settings from /home/scur2687/.config/wandb/settings
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_setup.py:_flush():67] Loading settings from /gpfs/home5/scur2687/erwin/experiments/wandb/settings
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /gpfs/home5/scur2687/erwin/experiments/wandb/run-20250510_205255-gv7ml4up/logs/debug.log
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /gpfs/home5/scur2687/erwin/experiments/wandb/run-20250510_205255-gv7ml4up/logs/debug-internal.log
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_init.py:init():781] calling init triggers
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'model': 'erwin_nsa', 'data_path': '../../nico_directory/shapenet_car_processed', 'size': 'small', 'num_epochs': 100, 'batch_size': 2, 'use_wandb': 1, 'lr': 0.001, 'val_every_iter': 100, 'experiment': 'shapenet', 'test': 0, 'seed': 0, 'knn': 8, 'c_in': 64, 'c_hidden': 64, 'rotate': 0, 'depth': 6, 'num_heads': 8, 'compress_ball_size': 64, 'sliding_window_size': 32, 'num_selected_blocks': 1, '_wandb': {}}
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_init.py:init():809] starting backend
2025-05-10 20:52:55,840 INFO    MainThread:1695807 [wandb_init.py:init():813] sending inform_init request
2025-05-10 20:52:55,848 INFO    MainThread:1695807 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-10 20:52:55,848 INFO    MainThread:1695807 [wandb_init.py:init():823] backend started and connected
2025-05-10 20:52:55,853 INFO    MainThread:1695807 [wandb_init.py:init():915] updated telemetry
2025-05-10 20:52:55,920 INFO    MainThread:1695807 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-05-10 20:52:56,390 INFO    MainThread:1695807 [wandb_init.py:init():1014] starting run threads in backend
2025-05-10 20:52:56,903 INFO    MainThread:1695807 [wandb_run.py:_console_start():2454] atexit reg
2025-05-10 20:52:56,903 INFO    MainThread:1695807 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-05-10 20:52:56,903 INFO    MainThread:1695807 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-05-10 20:52:56,903 INFO    MainThread:1695807 [wandb_run.py:_redirect():2394] Redirects installed.
2025-05-10 20:52:56,912 INFO    MainThread:1695807 [wandb_init.py:init():1056] run started, returning control to user process
2025-05-10 20:52:56,912 INFO    MainThread:1695807 [wandb_watch.py:_watch():71] Watching
2025-05-10 20:52:56,915 INFO    MainThread:1695807 [wandb_run.py:_config_callback():1327] config_cb None None {'num_parameters': 3719169}
2025-05-10 20:53:26,903 INFO    MsgRouterThr:1695807 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
2025-05-10 20:53:26,904 ERROR   IntMsgThr :1695807 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-10 20:53:26,910 ERROR   IntMsgThr :1695807 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-10 20:53:26,911 ERROR   IntMsgThr :1695807 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-10 20:53:26,911 ERROR   IntMsgThr :1695807 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2381, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/home5/scur2687/erwin/erwin/lib64/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
